config/routes.rb
Rails.application.routes.draw do
  # resources :comments
  devise_for :authors
  #get 'articles/new'
  #get 'articles/index'
  resources :articles do
    resources :comments
  end
  
  get 'estaticas/contacto'
  get 'estaticas/nosotros'
  get 'estaticas/otra'
  #get 'home/index'
  #root 'home#index'
  root 'articles#index'

  get '*path' => redirect('/')
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author
  has_many :comment, dependent: :destroy
  validates :title, presence: { :message => "No puede ser vacio"}
  validates :content, presence: { :message => "No puede ser vacio"} , length: { minimum: 50, :message => "Demasiado corto" }
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #Authentication
  before_action :authenticate_author!, except: [:index, :show]
  before_action :correct_author, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all.order("created_at DESC").paginate(page: params[:page], per_page:2)
  end

  # Stores data in memory
  def new
    @button = "Create"
    @article = current_author.articles.build
  end
  # Stores data in database
  def create
    @article = current_author.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  # Stores data in memory
  def edit
    @button = "Modify"
    @article =  Article.find(params[:id])
  end

  # Stores data in database
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Articles successfully modified."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, :notice => "Articles successfully deleted."
  end

  #security
  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

  def correct_author
    @article = current_author.articles.find_by(id: params[:id])
    redirect_to articles_path, notice: "You are not authorized to edit this article." if @article.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:create, :destroy]

  # POST /comments or /comments.json
  def create
    # @article = Article.find(params[:article_id])
    @comment = @article.comment.create(comment_params)

    # redirect_to post_path(@article)
    redirect_to @article
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    # @article = Article.find(params[:article_id])
    @comment = @article.comment.find(params[:id])
    @comment.destroy

    redirect_to @article
  end

  private
    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:name, :text, :article_id)
    end

    def set_article
      @article = Article.find(params[:article_id])
    end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
    @id     = params[:id].to_i + 10
    @pagina = params[:pagina]
  end

  def nosotros
  end

  def otra
    @message = "Hello from controller"
    @users = ['Jorge', 'Juan', 'Ester']
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any?  %>
        <div id="errors">
            <h2> errors: </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
                <%end%>
            </ul>
        </div>
    <%end%>
    <div class="mb-3">
        <%= f.label :title ,class:"form-label" %>
        <%= f.text_field :title ,class:"form-control" %>
    </div>
    <div class="mb-3">
        <%= f.label :content ,class:"form-label" %>
        <%= f.text_area :content ,class:"form-control" %>
    </div>

    <%= f.submit "#{@button} Article" , class: "btn btn-primary"%> 
<%end%>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<% @articles.each do |art| %>
    <h2> <%= link_to art.title, art %></h2>
    <p> <small><%= art.created_at.strftime("%d-%m-%Y") %></small></p>
    <p> <%= art.content.truncate_words(30) %></p>
<%end%>

<%= will_paginate @articles %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><small>Create at: <%= @article.created_at.strftime("%d-%m-%Y") %></small></p>
<p><%= @article.content %></p>

<% if author_signed_in? %>
    <%= link_to "Edit", edit_article_path(@article)%>
    <%= link_to "Delete", @article, :method => :delete, data: {confirm: "Are you sure you want to delete the article?"} %>
<% end %>    

<p><% @article.comment.count %> Commets</p>
<%= render @article.comment %>
<br>
<p>Make a comment</p>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<div>
    <p><%= comment.name %></p>
    <p><%= comment.text %></p>
    <p> Create at <%= comment.created_at.strftime("%d-%m-%Y") %></p>
    <%= link_to "Delete", [comment.article, comment], :method => :delete, data: {confirm: "Are you sure you want to delete the article?"} %>

</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comment.build]) do |f| %>
  <div class="mb-3">
    <div class="field">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_area :name, class: "form-control"%>
    </div>
  </div>
  <div class="mb-3">
    <div class="field">
      <%= f.label :text, class: "form-label" %>
      <%= f.text_field :text, class:"form-control" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Publish", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/estaticas/contacto.html.erb
<% provide(:title, "Contacto") %>
<h1>Estaticas#contacto</h1>
<p>Find me in app/views/estaticas/contacto.html.erb</p>
<% #params.inspect %>
<p>ID: <%= params[:id] %></p>
<p>page: <%= params[:pagina] %></p>
<p>ID: <%= @id  %></p>
<p>page: <%= @pagina %></p>

app/views/estaticas/nosotros.html.erb
<% provide(:title, "Nosotros") %>
<h1>Estaticas#nosotros</h1>
<p>Find me in app/views/estaticas/nosotros.html.erb</p>

app/views/estaticas/otra.html.erb
<h1>Jorge</h1>

<% 1+1 %>
<%= 1+1 %>
<%# commmets%>

<% 5.times do |x|
    puts x
    end
%>

<% 5.times do |x| %>
    <%= x %>
    <%end%>

<%= @message %>
<br>
<%= "Controlller: #{@message}" %>
<ul>
    <% @users.each do |i| %>
        <%= "<li> #{i} </li>".html_safe %>
    <%end%>
</ul>

<%= link_to 'Home', root_path %>
<%= link_to 'Contacto', estaticas_contacto_path %>
<%= link_to 'Contacto',  
            {:controller => 'estaticas',
            :action => 'contacto',
            :id => 3,
            :pagina => 2,
            },
            :class => 'my-class',
            :target => '_blank'%>

<div class="alert alert-primary" role="alert">
  A simple primary alert—check it out!
</div>
<div class="alert alert-secondary" role="alert">
  A simple secondary alert—check it out!
</div>
<div class="alert alert-success" role="alert">
  A simple success alert—check it out!
</div>
<div class="alert alert-danger" role="alert">
  A simple danger alert—check it out!
</div>
<div class="alert alert-warning" role="alert">
  A simple warning alert—check it out!
</div>
<div class="alert alert-info" role="alert">
  A simple info alert—check it out!
</div>
<div class="alert alert-light" role="alert">
  A simple light alert—check it out!
</div>
<div class="alert alert-dark" role="alert">
  A simple dark alert—check it out!
</div>

app/views/home/index.html.erb
<% provide(:title, "My blog") %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <% if !flash.empty? %>
        <div class="alert alert-primary">
          <% flash.each do |key ,value| %>
            <li><%= value  %></li>
          <% end %>
        </div>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<%#= link_to 'Home', root_path %>
<%#= link_to 'Contacto', estaticas_contacto_path %>
<%#= link_to 'Nosotros', estaticas_nosotros_path %>

<%#= link_to 'Sign Up', new_author_session_path %>
<%#= link_to 'Sign Out', destroy_author_session_path, method: :delete %>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contacto', estaticas_contacto_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Nosotros', estaticas_nosotros_path,class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <% if !author_signed_in? %>
            <%= link_to 'Sign Up', new_author_session_path, class: "btn btn-primary me-2" %>
        <%else%>
            <%= link_to 'New article', new_article_path, class: "btn btn-warning me-2"%>
            <%= link_to 'Sign Out', destroy_author_session_path, class: "btn btn-danger",  method: :delete %>
        <%end%>
      </form>
    </div>
  </div>
</nav>